// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_VmkOb2beSEStI1s1otOEfxXGVTR8xK0',
    appId: '1:462662038246:web:0a9365b202e456ec858127',
    messagingSenderId: '462662038246',
    projectId: 'smart-care-hub-6519a',
    authDomain: 'smart-care-hub-6519a.firebaseapp.com',
    databaseURL: 'https://smart-care-hub-6519a-default-rtdb.firebaseio.com',
    storageBucket: 'smart-care-hub-6519a.firebasestorage.app',
    measurementId: 'G-3M151L78ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAsc95kAUkRcHXBqQY3C_RyTIT3LNUJTU',
    appId: '1:462662038246:android:51e6d3d00c83e4ac858127',
    messagingSenderId: '462662038246',
    projectId: 'smart-care-hub-6519a',
    databaseURL: 'https://smart-care-hub-6519a-default-rtdb.firebaseio.com',
    storageBucket: 'smart-care-hub-6519a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgtpYrNszWAHTlVtFysUPOEWCSp-H4x2o',
    appId: '1:462662038246:ios:b2ebbbf46b796487858127',
    messagingSenderId: '462662038246',
    projectId: 'smart-care-hub-6519a',
    databaseURL: 'https://smart-care-hub-6519a-default-rtdb.firebaseio.com',
    storageBucket: 'smart-care-hub-6519a.firebasestorage.app',
    iosBundleId: 'com.example.iotCw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgtpYrNszWAHTlVtFysUPOEWCSp-H4x2o',
    appId: '1:462662038246:ios:b2ebbbf46b796487858127',
    messagingSenderId: '462662038246',
    projectId: 'smart-care-hub-6519a',
    databaseURL: 'https://smart-care-hub-6519a-default-rtdb.firebaseio.com',
    storageBucket: 'smart-care-hub-6519a.firebasestorage.app',
    iosBundleId: 'com.example.iotCw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_VmkOb2beSEStI1s1otOEfxXGVTR8xK0',
    appId: '1:462662038246:web:67b2da7bead40055858127',
    messagingSenderId: '462662038246',
    projectId: 'smart-care-hub-6519a',
    authDomain: 'smart-care-hub-6519a.firebaseapp.com',
    databaseURL: 'https://smart-care-hub-6519a-default-rtdb.firebaseio.com',
    storageBucket: 'smart-care-hub-6519a.firebasestorage.app',
    measurementId: 'G-VQXFT6MWK1',
  );
}
